# run: conda env create --file environment.yml
name: RGMC
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - cuda-cudart=11.7
  - cudatoolkit=11.7
  - ipykernel=6.25
  - matplotlib=3.7
  - numpy=1.24
  - numpy-base=1.24
  - python=3.11
  - pytorch=2.0
  - pytorch-lightning=2.0
  - pytorch-mutex=1.0
  - scipy=1.11
  - torchaudio=2.0
  - torchmetrics=0.11
  - torchvision=0.15
  - tqdm=4.65
  - wandb=0.15