name: RGMC
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda-cudart=11.8.89
  - cuda-libraries=11.8.0
  - cuda-runtime=11.8.0
  - numpy=1.24.3
  - numpy-base=1.24.3
  - python=3.11.3
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-lightning=2.0.2
  - pytorch-mutex=1.0
  - torchaudio=2.0.2
  - torchmetrics=0.11.4
  - torchvision=0.15.2
  - tqdm=4.65.0
  - wandb=0.15.3