# run: conda env create --file environment.yml
name: RGMC
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - cuda-cudart=11.7
  - cudatoolkit=11.7
  - gym=0.26
  - ipykernel=6.25
  - matplotlib=3.7
  - numpy=1.24
  - pyglet=1.5
  - python=3.10
  - pytorch=2.0
  - pytorch-lightning=2.0
  - pytorch-mutex=1.0
  - scipy=1.11
  - torchaudio=2.0
  - torchmetrics=0.11
  - torchvision=0.15
  - tqdm=4.65
  - wandb=0.15
  - pip=23.3
  - pip:
    - pysine==0.9.2